// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataEntryAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Container", b =>
                {
                    b.Property<int>("ContainerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContainerID"));

                    b.Property<DateTime?>("Arrival")
                        .HasColumnType("datetime2");

                    b.Property<string>("ArrivalActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Available")
                        .HasColumnType("datetime2");

                    b.Property<string>("BOLBookingNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Berth")
                        .HasColumnType("datetime2");

                    b.Property<string>("BerthActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carrier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContainerNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Container");

                    b.Property<string>("ContainerSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("datetime2");

                    b.Property<string>("FPM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LoadToRail")
                        .HasColumnType("datetime2");

                    b.Property<string>("MainSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Offload")
                        .HasColumnType("datetime2");

                    b.Property<string>("OffloadActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PONumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PickupLFD")
                        .HasColumnType("datetime2");

                    b.Property<string>("PortOfDeparture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PortOfEntry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PortRailwayPickup")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProjectNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RailDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("RailDestination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RailETA")
                        .HasColumnType("datetime2");

                    b.Property<string>("RailPickupNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RailwayLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ReturnLFD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Returned")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Sail")
                        .HasColumnType("datetime2");

                    b.Property<string>("SailActual")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Shipline")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ShiplineID")
                        .HasColumnType("int");

                    b.Property<string>("ShipmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terminal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TerminalID")
                        .HasColumnType("int");

                    b.Property<string>("Transload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vendor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VendorIDNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VesselID")
                        .HasColumnType("int");

                    b.Property<string>("VesselLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VesselLineID")
                        .HasColumnType("int");

                    b.Property<string>("VesselName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Voyage")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContainerID");

                    b.ToTable("Containers", (string)null);
                });

            modelBuilder.Entity("Vessel", b =>
                {
                    b.Property<int>("VesselID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VesselID"));

                    b.Property<string>("VesselName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VesselID");

                    b.ToTable("Vessels", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
